### ISSUE TITLE
About example dataset

### ISSUE THREAD

**Issue by Philyzh8** [yyLIU12138/INSTINCT#1]
When reproducing according to your tutorial, where can I get the annadata type data of the example? Thanks

**Comment by yyLIU12138** [comment]
> When reproducing according to your tutorial, where can I get the annadata type data of the example? Thanks

To obtain these datasets, you can look at the Data Availability section at the end of our manuscript for help. Data samples are not directly offered with anndata type and you need to process them.

You can ask Zhen Li, who is also an author of this manuscript, for help to get to know about the preprocessing procedure for getting the anndata type data. You can get in touch with him through email lizhen22@mails.tsinghua.edu.cn.

Thanks for your interest in this work.
